import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'react/index': 'src/react/index.ts',
    'vanilla/index': 'src/vanilla/index.ts',
    'adapters/index': 'src/adapters/index.ts',
    'adapters/evm': 'src/adapters/evm.ts',
    'adapters/sui': 'src/adapters/sui.ts',
    'adapters/near': 'src/adapters/near.ts',
    'adapters/aptos': 'src/adapters/aptos.ts',
    'adapters/starknet': 'src/adapters/starknet.ts',
    'adapters/ton': 'src/adapters/ton.ts',
    'adapters/tron': 'src/adapters/tron.ts',
    // Chain providers — lazy-loaded by BlinkConnectProvider
    'react/chain-providers/SuiProvider': 'src/react/chain-providers/SuiProvider.tsx',
    'react/chain-providers/AptosProvider': 'src/react/chain-providers/AptosProvider.tsx',
    'react/chain-providers/StarknetProvider': 'src/react/chain-providers/StarknetProvider.tsx',
    'react/chain-providers/TonProvider': 'src/react/chain-providers/TonProvider.tsx',
    'react/chain-providers/TronProvider': 'src/react/chain-providers/TronProvider.tsx',
    // Chain views — lazy-loaded by ConnectModal
    'react/chain-views/SuiConnectView': 'src/react/chain-views/SuiConnectView.tsx',
    'react/chain-views/StarknetConnectView': 'src/react/chain-views/StarknetConnectView.tsx',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: true,
  treeshake: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    '@reown/appkit',
    '@reown/appkit/react',
    '@reown/appkit/networks',
    '@reown/appkit-adapter-wagmi',
    '@reown/appkit-adapter-solana',
    'wagmi',
    'wagmi/chains',
    'viem',
    '@tanstack/react-query',
    '@mysten/dapp-kit',
    '@mysten/sui/client',
    '@hot-labs/near-connect',
    '@aptos-labs/wallet-adapter-react',
    '@starknet-react/core',
    '@starknet-react/chains',
    '@tonconnect/ui-react',
    '@tronweb3/tronwallet-adapter-react-hooks',
    '@tronweb3/tronwallet-adapters',
  ],
  banner: {
    js: '"use client";',
  },
});
